In [1]:
import numpy as np

## numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [5]:
matrixListesi[0][0]

10

In [6]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.diag((2,2))

array([[2, 0],
       [0, 2]])

In [12]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [14]:
np.random.randn(4)

array([ 2.08371928, -1.31824213,  0.79139123, -0.07654257])

In [15]:
np.random.randn(3,3)

array([[ 0.82501942,  0.49146987,  0.29088957],
       [-0.22254538, -1.2522181 ,  0.61777764],
       [ 1.09857461, -1.51131845,  1.41238519]])

In [42]:
np.random.randint(1,5)

3

In [16]:
np.random.randint(1,49,6)

array([22,  7, 12, 36, 19, 11])

In [17]:
benimNumpyDizim=np.arange(30)

In [22]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
benimRandomDizim=np.random.randint(0,100,20)

In [29]:
benimRandomDizim

array([42, 33, 55, 89, 22, 43, 49, 57,  9, 90, 22, 33,  1, 85, 82, 74, 32,
       18, 11, 47])

## numpy dizi methodları

In [30]:
reshapeDizim=benimNumpyDizim.reshape(5,6)
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
benimRandomDizim.argmax()

9

In [32]:
benimRandomDizim.mean()

44.7

In [34]:
benimRandomDizim.sort()

In [35]:
benimRandomDizim

array([ 1,  9, 11, 18, 22, 22, 32, 33, 33, 42, 43, 47, 49, 55, 57, 74, 82,
       85, 89, 90])

In [60]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [61]:
reshapeDizim.shape

(5, 6)