In [3]:
import numpy as np

In [4]:
benimListem=[[10,20,30],[40,50,60],[70,80,90]]

In [18]:
benimListem

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [19]:
benimMatrixDizim=np.array(benimListem)

In [20]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
benimMatrixDizim[0]

array([10, 20, 30])

In [22]:
benimMatrixDizim[1][2]

60

In [23]:
benimMatrixDizim[1:,2]

array([60, 90])

In [25]:
benimMatrixDizim[1,1:]

array([50, 60])

In [26]:
yeniListem=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [27]:
yeniListem

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

In [30]:
yeniMatrix=np.array(yeniListem)

In [31]:
yeniMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
yeniMatrix[[3,2,0]]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

## operasyonlar

In [37]:
yeniBirDizi=np.random.randint(1,100,20)

In [38]:
yeniBirDizi

array([38, 83, 60, 64, 65, 61, 70, 31, 81, 94,  5, 76, 48, 63, 92, 60, 96,
       20, 70, 54])

In [43]:
sonucDizisi=yeniBirDizi > 24
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True])

In [44]:
yeniBirDizi[sonucDizisi]

array([38, 83, 60, 64, 65, 61, 70, 31, 81, 94, 76, 48, 63, 92, 60, 96, 70,
       54])

In [45]:
yeniBirDizi[yeniBirDizi>24]

array([38, 83, 60, 64, 65, 61, 70, 31, 81, 94, 76, 48, 63, 92, 60, 96, 70,
       54])

In [46]:
yeniIkinciDizi=np.random.randint(1,20,5)

In [47]:
yeniIkinciDizi

array([ 6,  2, 11, 15, 13])

In [54]:
yeniUcuncuDizi=np.arange(1,6)

In [55]:
yeniUcuncuDizi

array([1, 2, 3, 4, 5])

In [56]:
yeniIkinciDizi + yeniUcuncuDizi

array([ 7,  4, 14, 19, 18])

In [57]:
yeniIkinciDizi * yeniUcuncuDizi

array([ 6,  4, 33, 60, 65])

In [60]:
np.sqrt(yeniIkinciDizi)

array([2.44948974, 1.41421356, 3.31662479, 3.87298335, 3.60555128])

In [61]:
np.max(yeniUcuncuDizi)

5